# Generated by Django 4.2.4 on 2023-08-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(),
        ),
    ]
