# Generated by Django 4.2.4 on 2023-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='uid',
            field=models.CharField(default=0),
        ),
    ]
