# Generated by Django 4.2.4 on 2023-09-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_journey_delayedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('toc', models.CharField()),
                ('passengerSvc', models.BooleanField(default='false')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='toc',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, related_name='TOC_toc', to='timetable.toc'),
            preserve_default='true',
        ),
    ]
