# Generated by Django 4.2.4 on 2023-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_toc_journey_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toc',
            name='passengerSvc',
            field=models.BooleanField(default='False'),
        ),
    ]
