# Generated by Django 4.2.4 on 2023-09-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_toc_passengersvc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='crs',
        ),
    ]
