# Generated by Django 4.2.4 on 2023-09-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_remove_station_crs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig', models.CharField(default=0)),
                ('dest', models.CharField(default=0)),
                ('toc', models.CharField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField()),
                ('route_id', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, related_name='Route_id', to='timetable.route')),
                ('station_id', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, related_name='Station_name', to='timetable.station')),
            ],
        ),
    ]
