# Generated by Django 4.2.4 on 2023-09-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_route_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='station_id',
            new_name='station',
        ),
    ]
