# Generated by Django 4.2.4 on 2023-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration_checksum',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='stop',
            name='next_stop_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
