# Generated by Django 4.2.4 on 2023-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_route_duration_checksum_stop_next_stop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='time_from_last',
            field=models.DurationField(null='true'),
        ),
    ]
