# Generated by Django 4.2.4 on 2023-10-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_stop_next_stop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='duration_checksum',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='next_stop_time',
        ),
    ]
