# Generated by Django 4.2.4 on 2023-10-06 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_remove_route_duration_checksum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DurationField(null='true')),
                ('route', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='delay_route_id', to='timetable.route')),
                ('stop', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='delay_stop_id', to='timetable.stop')),
                ('toc', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='delay_toc_id', to='timetable.toc')),
                ('train', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='delay_train_id', to='timetable.train')),
            ],
        ),
    ]
